GPU: Tesla T4
Loading Model
Traceback (most recent call last):
  File "train.py", line 250, in <module>
    checkpoint_path=args.initial_checkpoint)
  File "/home/ubuntu/workspace/vision.pjt/timm/models/factory.py", line 81, in create_model
    model = create_fn(pretrained=pretrained, **kwargs)
  File "/home/ubuntu/workspace/vision.pjt/timm/models/pit.py", line 276, in pit_b_224
    return _create_pit('pit_b_224', pretrained, **model_kwargs)
  File "/home/ubuntu/workspace/vision.pjt/timm/models/pit.py", line 261, in _create_pit
    **kwargs)
  File "/home/ubuntu/workspace/vision.pjt/timm/models/helpers.py", line 438, in build_model_with_cfg
    model = model_cls(**kwargs) if model_cfg is None else model_cls(cfg=model_cfg, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'global_pool'